name: Manual Approve

on:
  release:
    types: [published]
  push:
  
permissions:
      id-token: write   
      contents: read   
 
jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    #environment: manual-jobs
    outputs:
      output1: ${{ steps.deploy.outputs.endpoint }}
    steps:
      - name: Get The Code
        uses: actions/checkout@v3
      - name: Requisites
        uses: ./.github/prepare
      - name: Download the model
        id: deploy
        run: |
          echo "prepared with for $API_ADDR"
          pwd && ls -l
          echo "endpoint=https://test.hello/" >> "$GITHUB_OUTPUT"
      - name: Clean-up
        if: failure()
        run: |
          echo "endpoint is ${{ steps.deploy.outputs.endpoint }}"
          echo "clean-up done!"
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [deploy]
    steps:
      - name: Run tests
        env:
          OUTPUT1: ${{needs.deploy.outputs.output1}}
        run: |
          echo $OUTPUT1
          exit 1
          echo "done!"

  cleanup:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    needs: [deploy, test]
    steps:
      - name: Get The Code
        uses: actions/checkout@v3
      - name: Requisites
        uses: ./.github/prepare
      - name: Run tests
        env:
          OUTPUT1: ${{needs.deploy.outputs.output1}}
        run: |
          echo $OUTPUT1
          echo "done!"
